name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install
      - name: Install and test
        uses: koenhagen/measure-energy-action@v0.33
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: yarn test:app
          count: 1
